/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface JoyCon {
    'left': string;
    'right': string;
    'side': "L" | "R";
  }
  interface JoyConAttributes extends StencilHTMLAttributes {
    'left'?: string;
    'onAxes'?: (event: CustomEvent) => void;
    'onButton'?: (event: CustomEvent) => void;
    'right'?: string;
    'side'?: "L" | "R";
  }
}

declare global {
  interface StencilElementInterfaces {
    'JoyCon': Components.JoyCon;
  }

  interface StencilIntrinsicElements {
    'joy-con': Components.JoyConAttributes;
  }


  interface HTMLJoyConElement extends Components.JoyCon, HTMLStencilElement {}
  var HTMLJoyConElement: {
    prototype: HTMLJoyConElement;
    new (): HTMLJoyConElement;
  };

  interface HTMLElementTagNameMap {
    'joy-con': HTMLJoyConElement
  }

  interface ElementTagNameMap {
    'joy-con': HTMLJoyConElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
