/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface JoyCon {
    'left': string;
    'right': string;
    'side': 'L' | 'R';
  }
}

declare namespace LocalJSX {
  interface JoyCon extends JSXBase.HTMLAttributes {
    'left'?: string;
    'onAxes'?: (event: CustomEvent<any>) => void;
    'onButton'?: (event: CustomEvent<any>) => void;
    'right'?: string;
    'side'?: 'L' | 'R';
  }

  interface ElementInterfaces {
    'JoyCon': Components.JoyCon;
  }

  interface IntrinsicElements {
    'JoyCon': LocalJSX.JoyCon;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLJoyConElement extends Components.JoyCon, HTMLStencilElement {}
  var HTMLJoyConElement: {
    prototype: HTMLJoyConElement;
    new (): HTMLJoyConElement;
  };
  interface HTMLElementTagNameMap {
    'joy-con': HTMLJoyConElement
  }

  interface ElementTagNameMap {
    'joy-con': HTMLJoyConElement;
  }
}

